apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-cstate-override
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  kernelArguments:
    - intel_idle.max_cstate=1
    - processor.max_cstate=1